steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '-f', '$_DOCKERFILE', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '$_MEMORY'
      - '--cpu'
      - '$_CPU'
      - '--timeout'
      - '$_TIMEOUT'
      - '--min-instances'
      - '$_MIN_INSTANCES'
      - '--max-instances'
      - '$_MAX_INSTANCES'
substitutions:
  _SERVICE_NAME: cisco-automation-certification-station
  _REGION: us-central1
  _MEMORY: 2Gi
  _CPU: '2'
  _TIMEOUT: 300s
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _DOCKERFILE: Dockerfile.fastapi
images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
timeout: 1800s
