apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cisco-automation-chatbot
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Auto-scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # Resource allocation
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1"
        # Timeout for requests
        run.googleapis.com/timeout: "300s"
    spec:
      containerConcurrency: 10
      containers:
      - image: gcr.io/PROJECT_ID/cisco-automation-chatbot
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: cisco-chatbot-secrets
              key: google-api-key
        - name: SERPAPI_KEY
          valueFrom:
            secretKeyRef:
              name: cisco-chatbot-secrets
              key: serpapi-key
        - name: EMBEDDING_MODEL
          value: "paraphrase-MiniLM-L3-v2"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "0.5"
        # Startup and liveness probes
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 5
