steps:
  # Build the container image using the FastAPI Dockerfile with no cache
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-f', 'Dockerfile.fastapi', '-t', 'gcr.io/$PROJECT_ID/cisco-automation-certification-station', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cisco-automation-certification-station']

images:
  - 'gcr.io/$PROJECT_ID/cisco-automation-certification-station'

timeout: '1800s'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'