
[server]
# Server settings
headless = true
enableCORS = true
enableXsrfProtection = false
port = 8502
address = "0.0.0.0"

[browser]
# Browser settings
serverAddress = "localhost"
gatherUsageStats = false

[theme]
# Theme settings
base = "light"
            